### ISSUE TITLE
release_master

### ISSUE THREAD

**Issue by TheWudu** [taskrabbit/makara#21]
Hello!

In a version there has been the `release_master!` function to release the master stuck after some circumstances. 

This method has gone in latest beta `0.2.0.beta3`. 

Is there a possibilty to easy release the master after some inserts/updates? Because when updating some status-fields, which are not application-critical when they are inconsistent within one request, it would be nice to return to slave usage on selects. 

I found the possibility to override the `should_stick?` method. But then I have to put all cases in there, which isn't pretty. f.e:

return false if sql.to_s =~ /my_status_field/

Any hints?

**Comment by mnelson** [comment]
The release of the master pool is accomplished by changing Makara's context. This is done naturally in your app via the Makara middleware. In you controller you could have a helper method like:

``` ruby
def release_makara!
  ctxt = Makara::Context.generate
  Makara::Context.set_current ctxt
end
```

If it's your intention to truly release master, ignoring what happened in the previous request as well as this one, you would also add:

``` ruby
Makara::Context.set_previous ctxt
```
