### ISSUE TITLE
record not found on master

### ISSUE THREAD

**Issue by lasssim** [taskrabbit/makara#25]
hi,

we have some troubles understanding how your gem works.

here are our problems:
### problem 1:

we have multiple services that currently share a single DB. service A (java) creates records, lets call them posts. service A notifies service B (rails) about the new record. service B tires to fetch the record from the DB. makara tells service B to use the slave, but the replication lag sometimes is to big so service B will not be able to find the record.
#### possible fix:

we could catch all record not found exceptions in application controller and retry the whole request with "stick to master" if the query that raised the exception was called on a slave.
i'm not really happy with this approach but i don't see any other option at the moment. 
- i couldn't find a way to find out if a query was executed on a slave. how could i do that?
- how can i stick an ongoing request to the master?
### problem 2 (slightly different):

service B (rails) creates a new article in the DB and then shares this article on facebook. the facebook crawler then crawls the the show page of the article and makara has no chance to rely on the cookie to dispatch queries to the master if the crawler hits the page before the master_ttl expires.
#### possible fix:

we could add the correct context to the url we shared and adjust the middleware to respect the get parameter.

i think that makara was designed for "simple" web applications that are used by browsers/users only and not for scenarios like ours. but i think with a few tweaks it would fit our needs and i would really love to help and figure these issue out.

br, simon

**Comment by mnelson** [comment]
@lister mind taking a look at #26?
