### ISSUE TITLE
not able install gem

### ISSUE THREAD

**Issue by nikhilvs** [taskrabbit/makara#28]
After giving "gem 'makara', git: 'git@github.com:taskrabbit/makara.git', tag: 'v0.2.0.beta9'" in Gemfile and when does the 'bundle install' gets the following error :+1: 

Permission denied (publickey).
fatal: Could not read from remote repository.

"Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone 'git@github.com:taskrabbit/makara.git' "/home/nikhilvs9999/.rvm/gems/ruby-1.9.3-p448/cache/bundler/git/makara-d929f6b77aa149f0be81a67ac1a27255af446fe3"
--bare --no-hardlinks` in directory /home/nikhilvs9999/RAILS/rails_aptana_workspace/api-server has failed. "

**Comment by nikhilvs** [comment]
ok gave this one in Gemfile :+1: 

gem 'makara',:git => 'git://github.com/taskrabbit/makara.git',tag: 'v0.2.0.beta9'

And its working

**Comment by lserman** [comment]
Using git:// worked for me too, this is what should be in the README.

**Comment by mnelson** [comment]
Updated
