### ISSUE TITLE
.lock! method performed on slaves instead of master

### ISSUE THREAD

**Issue by rrix-storehouse** [taskrabbit/makara#30]
We're doing database locking in one of our API callbacks, and this has broken since moving to makara. PostgreSQL handles locking using a SELECT FOR UPDATE a la `SELECT "video_representations".* FROM "video_representations" WHERE "video_representations"."id" = $1 LIMIT 1 FOR UPDATE`

[MakaraAbstractAdapter](https://github.com/taskrabbit/makara/blob/master/lib/active_record/connection_adapters/makara_abstract_adapter.rb#L52)'s regex doesn't catch this. I'm working on a fixed up regex right now but I'm a bit rusty in that department. failing that, i can work around this by doing a VideoRepresentation.touch or so to promote the request to master myself, but this is still, imo, a bug in the `#needs_master` method. If a single regex cannot cover this, a SQL_FORCE_MASTER regex which can catch SELECT FOR UPDATE coudl be inserted in to `#needs_master`, either way, I'm willing to submit the pull request for that. :)

**Comment by mnelson** [comment]
Sorry about the oversight.

I had a look ahead matcher but it's just confusing to look at. Opted for the separate master expressions. See if the locking-select-sql branch handles the problems you were encountering. Thanks for taking the time.

**Comment by rrix-storehouse** [comment]
Wow, thanks! I appreciate the quick response. :+1:

**Comment by mnelson** [comment]
v0.2.0.beta10 has the fixes for this. Please let me know if you see any other issues with a pg setup. Cheers
