### ISSUE TITLE
rspec transaction rollback errors

### ISSUE THREAD

**Issue by meltingice** [taskrabbit/makara#42]
When running rspec, every test outputs the error:

```
/Users/ryanlefevre/.rvm/gems/ruby-2.0.0-p353/bundler/gems/makara-fd03ae9cee58/lib/makara/proxy.rb:81:in `block in respond_to_missing?': delegator does not forward private method #rollback_transaction_records
```

Environment:
- Ruby 2.0.0
- Rails 3.2.16
- Rspec 2.14.1
- database_cleaner 1.2.0

**Comment by mnelson** [comment]
At TaskRabbit we don't use makara in the test environment because things get very screwy with transactions. SimpleDelegator is sending that message: https://github.com/ruby/ruby/blob/trunk/lib/delegate.rb#L101. Looks like we could opt out of calling super() if include_private=true.

**Comment by mnelson** [comment]
@meltingice master has updates which should resolve this specific issue. Let me know if that solves your issues and I'll tag it.

**Comment by meltingice** [comment]
Yeah, I ended up switching to normal mysql2 for the test environment. I can confirm that this is fixed in master, though.

Thanks!
