### ISSUE TITLE
Rails 4 Compatible?

### ISSUE THREAD

**Issue by jdowning** [taskrabbit/makara#45]
I am having some performance issues with using the makara gem with Rails 4. After upgrading an application and generating some requests, I notice the response time is _much_ slower. I updated the `database.yml` to use the postgresql adapter instead of the makara-postgresql adapter and normal response times resumed. For example:

With makara-postgresql:  X-Runtime: 4.144442
WIth postgresql:  X-Runtime: 0.755197

I have looked at several different reasons why this could happen, and changing the adapter seems to be the cause here. We do have another application that uses Rails 4 and the makara-postgresql adapter with no known performance reduction. I see that you have compatibility for Active Record 4 (https://github.com/taskrabbit/makara/blob/master/lib/active_record/connection_adapters/makara_postgresql_adapter.rb#L4), though neither the README or the Task Rabbit blog post indicate Rails 4 compatibility. 

Any ideas why one application would be adversely affected by the use of the adapter using Rails 4?

**Comment by mnelson** [comment]
We run Makara w/ Rails 4 @ TaskRabbit for our UK app and have average response times under 300ms. We're using mysql, however. Try switching to version 0.2.0.beta10. If that fixes it then I have a likely cause for the issue (#35).

**Comment by jdowning** [comment]
@mnelson Thanks again for your quick response. Upon further investigation, it appears the issue was traced to the newrelic_rpm gem. A recent upgrade introduced the latency and rolling back corrected the response time. I can confirm that both of our applications are using makara + postgresql on Rails 4 now. :smile:

**Comment by mnelson** [comment]
Hah! Excellent (for me at least). Do you have any idea why the combination of the new NR gem and makara 0.2.x conflicted? It may be an issue worth noting in the readme or at least in this thread.

**Comment by mnelson** [comment]
Also, fwiw we're running newrelic_rpm as well (3.6.6.147).

**Comment by jdowning** [comment]
I do not (yet). I have a support ticket in with them now. I downgraded from 3.7.2 to 3.6.5.130 and all is well. Something likely occurred between there.

**Comment by jonchay** [comment]
We're having this issue as well. @justindowning has there been any developments from the support ticket submitted to NewRelic?

**Comment by trobrock** [comment]
Getting this on newrelic (3.9.0.229), is there any work ongoing to address this? Or has there been any investigation into the root cause?

**Comment by mcansky** [comment]
getting ready to use Makara, any updates on this issue ? are newer versions of the new relic gem solving the issue ? I could not spot anything on the new relic changelog.

**Comment by trobrock** [comment]
I just confirmed 3.9.4.245 still does not work.

**Comment by mnelson** [comment]
@trobrock what version of makara? The 0.3.0  rc's might have resolved the problem by removing the initial connection logic. I haven't tested against NR as we're using Skylight now.

**Comment by trobrock** [comment]
I am using 0.2.2. I will try with 0.3.0 later and report back.

**Comment by mnelson** [comment]
Awesome, thank you.

**Comment by trobrock** [comment]
Just confirmed, 0.3.0.rc3 still has the performance issues with the latest newrelic gem.

**Comment by mcansky** [comment]
That is troublesome. Any report of similar performance issues with skylight and (or) a custom statsd based collection of metrics ?

**Comment by mnelson** [comment]
I haven't heard of anything else.

**Comment by blaibu** [comment]
Saw the giant performance warning on homepage that doesn't mention Rails 4 but noticed that this thread seems to only deal with Rails 4. Is the performance hit with makara + newrelic_rpm an issue on Rails 3? (If not, worth noting that on the warning on the homepage).

**Comment by mcansky** [comment]
I agree with @blaibu : the warning sign is helpful to know there are risks but it's hard to proceed from there with some degree of confidence and several steps of performance testing.

In our case (Rails 3.2.19, Ruby 2.1.2 and 1.9.3) we did not spot such big performance issue when testing with a recent New Relic version.
How could we put together a list of known working versions between Rails, Ruby, Makara and NewRelic ?
