### ISSUE TITLE
Unicorn and lazy loaded connection pool?

### ISSUE THREAD

**Issue by ksheurs** [taskrabbit/makara#47]
Not an issue, just a quick question!

We're interested in checking out makara. How does this work with the typical unicorn/rails setup where connections to the master are established at time of fork.

In order to scale out reads, ideally this connection to the master is lazy loaded or these initial connections are only to a pool of slaves? Does makara address this? Thanks!

**Comment by mnelson** [comment]
Makara holds a connection instantiation block in memory until an action is attempted on a connection (https://github.com/taskrabbit/makara/blob/master/lib/makara/connection_wrapper.rb#L61). If master was never used, the connection block would likely not be called. That said, ActiveRecord::Base.establish_connection will likely call a SET operation or something similar which would invoke and instantiate all connections. 

In general, Makara decides where the traffic should flow -- so if you have a read-heavy application the master connection (likely a pool of 1) would rarely be used and your slave pool (likely a pool of many slaves) would handle all your READ traffic. I wouldn't worry about each of your unicorns creating a single connection to your Master DB. It likely won't have any impact on the performance of SQL operations in your app or the scalability of your app. The only time it would make a difference is if you were approaching the max # of connections for your DB instance.

As far as the unicorn setup, the before/after_fork look normal. Makara is a drop-in replacement for your existing DB adapter. Check out this comment for an example: https://github.com/taskrabbit/makara/issues/38#issuecomment-34130701

**Comment by ksheurs** [comment]
cool thanks @mnelson! very helpful. our only concern is actually the max # of connection issue on our master, so i will do some testing to see if any SET operations are happening.. perhaps it's fine tho as you mention.

any specific reason those SET's can't be in the connection instantiation block too? seems like they would only be needed if an INSERT/UPDATE/DELETE was to happen. thanks again!

**Comment by mnelson** [comment]
Those SET's require the connection, so the cause is the SET and the effect is the instantiation. Other than caching them and executing them all on the first SELECT / INSERT / etc I'm not sure how we would be able to defer that.
