### ISSUE TITLE
error running "rails dbconsole" when using makara_mysql2 DB adapter

### ISSUE THREAD

**Issue by quarklemotion** [taskrabbit/makara#49]
When using the makara_mysql2 adapter, running "rails dbconsole" (in rails v3.2+) results in the following error:

"Unknown command-line client for my_database. Submit a Rails patch to add support!"

Looking at the rails source code, if the makara adapter were named/aliased mysql2_makara, then dbconsole work work.  The adapter name is not matching any of the rails expected adapter name prefixes:

See: https://github.com/rails/rails/blob/3-2-stable/railties/lib/rails/commands/dbconsole.rb

**Comment by mnelson** [comment]
Name aliases added in the 0.3.0.rc2

**Comment by stwr667** [comment]
See https://github.com/taskrabbit/makara/pull/210 for a fix to this.
