### ISSUE TITLE
Ruby 2.0 always returns nil

### ISSUE THREAD

**Issue by indirect** [taskrabbit/makara#5]
As part of deploying an HTTP service that depends on makara, we've discovered that Makara is not compatible with Ruby 2.0. On Ruby 2.0 (unlike on Ruby 1.9.3), all invocations of the #execute method return nil. The Makara test suite passes on Ruby 2.0 with no problems, but it fails to test for this particular issue.

When running the Makara test suite against Postgres on 1.9.3 and 2.0, I was able to reliably reproduce this issue — on 1.9.3, Makara executed SQL queries against the database, and on 2.0.0, Makara did not execute the SQL query, and simply returned nil without raising an error.

**Comment by mnelson** [comment]
Alright, I dug into this a bit but could never find a solution. As you already know there was an issue with the initial releases of ruby 2.0 which caused this. I personally can't get this to happen locally but it happens on travis (still - https://travis-ci.org/taskrabbit/makara/builds/10040694). I'll keep the issue open and test when new 2.0 patches are released. As of now, p247 is the latest and it's still busted... but not all the time.

**Comment by indirect** [comment]
I reported this bug to the ruby bugtracker, and it was fixed. As far as I know, this particular workaround is only needed for ruby 2.0.0-p0.

**Comment by mnelson** [comment]
So the issues on Travis are actually the inverse of this - the abstract adapter does not define #execute but defined?(super) is evaluating as true in some circumstances.

```
Failure/Error: lambda{
expected no Exception, got #<NoMethodError: super: no superclass method `execute' for #<ActiveRecord::ConnectionAdapters::AbstractAdapter:0x00000003f53b80>> with backtrace:
```

 It might be related to the usage of `undef_method` in activerecord (pulling from 4.0.0)

```
# Executes the SQL statement in the context of this connection.
def execute(sql, name = nil)
end
undef_method :execute
```

**Comment by mnelson** [comment]
Unless someone is using the abstract adapter, the secondary issue noted in the previous comment will not be an issue in any ruby version. Closing
