### ISSUE TITLE
Database connections not closing

### ISSUE THREAD

**Issue by ChrisHughes** [taskrabbit/makara#53]
Not sure if this relates to makara or not, but we are seeing database connections sit in TIME_WAIT for 8 hours on our rails servers running passenger, leading to massive numbers of connections on our database. This happens during normal operation over many hours, not during startup / shutdown.
This eventually leads to our main database reaching its connection limit. This happens to both read and write databases, but only affects our write database as connections from 4 server regions are coming in to it.
Restarting nginx in our case causes the connections to close and drop down to normal levels, which then will creep up again over the next 8 - 12 hours. Any ideas on this would be greatly appreciated. Thanks.
Screenshot shows our database connections when they change over and the effect a restart has http://cl.ly/image/3R1i141T3L0m

**Comment by ChrisHughes** [comment]
I've reached out to Phusion's support for Passenger on this issue as well. Their response seems to suggest looking in to whether connections are closed using the normal ActiveRecord events. To quote a section of their reply:

> It could be that they are connections created during the preloading, which should have been reestablished during worker creation but for some reason were left alone. I see that Makara
> manages multiple connection, could it be that it has connections that are not in the ActiveRecord connection pool and therefore not cleared by ActiveRecord::Base.clear_all_connections! ?
> 
> To get to the bottom of this we would need some information about what happens when your workers restart. 
> 
> You can read a little about how you can reestablish connections with Passenger here:
> 
> https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#_smart_spawning_caveat_1_unintentional_file_descriptor_sharing
> 
> But note that for ActiveRecord this is done automatically, you can see how we do it here, perhaps the Makara team could say whether this is compatible with their proxy adapter:

**Comment by mnelson** [comment]
So maybe adding `clear_all_connections!` to https://github.com/taskrabbit/makara/blob/master/lib/active_record/connection_adapters/makara_abstract_adapter.rb#L64 might help. I assume the other similar methods in AR would have to behave the same way.

**Comment by mnelson** [comment]
Any chance all your leftover connections are to your slaves?

**Comment by ChrisHughes** [comment]
I can try adding clear_all_connections! and see if that works.

The leftover connections appear to be to both master and slave dbs. Our master is in contention however because all 4 Amazon regions we operate connect back into the one master, whereas the slave dbs are nowhere near their connection count ceilings.

**Comment by mnelson** [comment]
We've seen this at TaskRabbit, @evantahler what say you? Are we still seeing this nowadays? (We roll our unicorns every couple hours no matter what)

**Comment by ChrisHughes** [comment]
I've pushed your change to our servers, will see in around 8 hours what happens. Thanks!

**Comment by mnelson** [comment]
Thanks so much. I apologize for the late reply. We're out straight over here.

**Comment by mnelson** [comment]
Any update on this?

**Comment by ChrisHughes** [comment]
We didn't see any immediate change with the patch applied, so it would be hard to know if it was fixed by it or not. However our connection count graph is much more steady. Amazon went through a two week period with a bug in their connection count reporting, meaning our graph was much more continuous with fewer jumps in connection count. Once that was resolved, our levels went back to almost what they were before, so we see some variation, but nothing that sets us over our connection limit to RDS.
So as the evidence is not clear on what resolved it, I will try removing your patch from our production servers and see if the issue returns or not.

**Comment by mnelson** [comment]
Reading through AR again to see if there's something we can do to makara for this I realized that `clear_all_connections!` is at the AR pool level, so Makara shouldn't effect this. Next time I work through issues I'll close this unless you say otherwise, @ChrisHughes.
