### ISSUE TITLE
using multiple top-level configs with maraka, is this supported/workaround?

### ISSUE THREAD

**Issue by mattcamuto** [taskrabbit/makara#6]
hi

we are using makara and it works great, when we have one DB configuration but we have some apps that use multiple top level configurations. e.g.

development:
  adapter: makara
  db_adapter: mysql2
  host: production_read_only
  //// other fields left out for brevity
databases:
- name: master
   role: master
   host: production_read_write
- name: slave
   role: slave
   host: production_read_only
  marketing_development:
  adapter: makara
  db_adapter: mysql2
  host: marketing_read_only
  //// other fields left out for brevity
  databases:
- name: master
   role: master
   host: marketing_read_write
- name: slave
   role: slave
   host: marketing_read_only

We have some isolated models that switch between connections using the standard 'establish_connection' usage. Example:

class User < ActiveRecord::Base <- Always uses development makara config
end

class MarketingSomething < ActiveRecord::Base 
establish_connection("marketing_#{Rails.env}") <- For example
end

This works fine and dandy when using the mysql2 gem. However what happens when using makara is that it starts off using the correct makara adapter (marketing_development) but then finally falls back to the 'developent' makara adapter for which then breaks the queries. Ultimatly I figured out the following line of code

../decorator.rb
  adapter = Makara.connection <--------
        if adapter && !adapter.hijacking?

makara.rb
 def connection
      return nil unless ActiveRecord::Base.connection.respond_to?(:unstick!)
      ActiveRecord::Base.connection
    end

Ultimately the Makara.connection will always return the 'development' connection based on the above line.

We have been trying a wide number of ways over the last few days to overcome this and to stash 'last known makara adapter' be it in thread current variables or similar to no avail.

I was wondering if anybody using makara and reading this have had such situations. We are in the process of 'one database/cluster per logical application' but right now we do connect to multiples. 

any help is appreciated in advance.

**Comment by kigster** [comment]
Matt, we tried doing that at Wanelo, and also discovered that Makara only supports a single master->slave configuration in database.yml.  You can not have another database split into read/writes from the same process.  

To resolve this, we moved a small piece of functionality that was around one large database table into a light-weight JSON Sinatra service.  The service then uses Makara backend with one master and many slaves.  

We also looked at dbCharmer instead of Makara, but that had even more problems and was not thread safe (so can't use with sidekiqs). 

Hope this helps.

**Comment by mnelson** [comment]
Hey guys, we're gonna be experimenting with a few things this week to get
us to a threadsafe world. I'll reference this issue when commits start
rolling in. Cheers

On Monday, May 20, 2013, Konstantin Gredeskoul wrote:

> Matt, we tried doing that at Wanelo, and also discovered that Makara only
> supports a single master->slave configuration in database.yml. You can not
> have another database split into read/writes from the same process.
> 
> To resolve this, we moved a small piece of functionality that was around
> one large database table into a light-weight JSON Sinatra service. The
> service then uses Makara backend with one master and many slaves.
> 
> We also looked at dbCharmer instead of Makara, but that had even more
> problems and was not thread safe (so can't use with sidekiqs).
> 
> Hope this helps.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/taskrabbit/makara/issues/6#issuecomment-18182108
> .

## 

Mike Nelson | *TaskRabbit | *Infrastructure Engineer

_C:_ 207.754.8828 *F: *415.795.1760

**Comment by mattcamuto** [comment]
Thanks so much for the response. We have been testing it and it working quite well. The only gotcha is this one with all the indirection in the AR control flow. Fantastic work!

**Comment by mnelson** [comment]
@mattcamuto just tagged https://github.com/taskrabbit/makara/releases/tag/v0.1.0.beta5 which should allow multiple db configurations.

**Comment by mattcamuto** [comment]
Thanks. We dropped in the v0.1.0 version a while ago with no problems (sans having to reset makara post_fork while using passenger, which makes sense). when i get back to work post maternity-leave we will upgrade. if the passenger issue is still there i will update the readme and issue pull request. thanks so much. this was great soln.
