### ISSUE TITLE
PG adapter for The foreman

### ISSUE THREAD

**Issue by diffnull** [taskrabbit/makara#60]
database.yaml:
production:
  adapter: postgresql_makara
  database: foreman
  username: foreman
  password: ***
  host: localhost
  makara:
    blacklist_duration: 5
    master_ttl: 5
    sticky: true

output:
[....] Restarting : foreman/usr/share/foreman/vendor/ruby/1.9.1/bundler/gems/makara-e5e9f2af855c/lib/makara/config_parser.rb:65:in `all_configs': undefined method`map' for nil:NilClass (NoMethodError)
        from /usr/share/foreman/vendor/ruby/1.9.1/bundler/gems/makara-e5e9f2af855c/lib/makara/config_parser.rb:48:in `master_configs'
        from /usr/share/foreman/vendor/ruby/1.9.1/bundler/gems/makara-e5e9f2af855c/lib/makara/proxy.rb:206:in`instantiate_connections'
        from /usr/share/foreman/vendor/ruby/1.9.1/bundler/gems/makara-e5e9f2af855c/lib/makara/proxy.rb:51:in `initialize'
        from /usr/share/foreman/vendor/ruby/1.9.1/bundler/gems/makara-e5e9f2af855c/lib/active_record/connection_adapters/makara_abstract_adapter.rb:131:in`initialize'
        from /usr/share/foreman/vendor/ruby/1.9.1/bundler/gems/makara-e5e9f2af855c/lib/active_record/connection_adapters/postgresql_makara_adapter.rb:19:in `new'
        from /usr/share/foreman/vendor/ruby/1.9.1/bundler/gems/makara-e5e9f2af855c/lib/active_record/connection_adapters/postgresql_makara_adapter.rb:19:in`postgresql_makara_connection'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in`checkout_new_connection'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in`loop'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
        from /usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in`block in connection'
        from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in`connection'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in`retrieve_connection'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/model_schema.rb:310:in`clear_cache!'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activerecord-3.2.18/lib/active_record/railtie.rb:103:in `block (2 levels) in <class:Railtie>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:418:in`_run__192062860__prepare__306838575__callbacks'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:405:in `__run_callback'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:385:in`_run_prepare_callbacks'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/reloader.rb:74:in`prepare!'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/actionpack-3.2.18/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/application/finisher.rb:47:in`block in module:Finisher'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/initializable.rb:30:in`run'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/initializable.rb:54:in`each'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/application.rb:136:in`initialize!'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /usr/share/foreman/config/environment.rb:5:in`<top (required)>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in `require'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in`block in require'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/activesupport-3.2.18/lib/active_support/dependencies.rb:251:in`require'
        from /usr/share/foreman/config.ru:3:in `block in <main>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in`instance_eval'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
        from /usr/share/foreman/config.ru:in`new'
        from /usr/share/foreman/config.ru:in `<main>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in`eval'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:200:in`app'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands/server.rb:46:in `app'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:304:in`wrapped_app'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands/server.rb:70:in`start'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands.rb:55:in `block in <top (required)>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands.rb:50:in`tap'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.18/lib/rails/commands.rb:50:in `<top (required)>'
        from script/rails:6:in`require'
        from script/rails:6:in `<main>'
 failed!

**Comment by mnelson** [comment]
You're missing the connections array in your config.

**Comment by diffnull** [comment]
oh, thank!
