### ISSUE TITLE
Uncaught exception: cannot load such file

### ISSUE THREAD

**Issue by smikkelsen** [taskrabbit/makara#64]
I cannot for the life of me get this to work. I've tried 0.3.0 rc2 and rc3. i've tried 0.2.2, but everything I try yields the same results. When I go to start the server, I get this:

Uncaught exception: cannot load such file -- <full path to my app>.../gems/activerecord-import-0.3.1/lib/activerecord-import/active_record/adapters/makara_mysql2_adapter

ruby-1.9.3-p484
Rails 3.2.15

development:
  adapter: makara_mysql2 (also tried mysql2_makara)
  encoding: utf8
  reconnect: true
  database: ****
  pool: 15
  username: ****
  password: ****
  makara:
    blacklist_duration: 5
    master_ttl: 5
    sticky: true
    rescue_connection_failures: false
    connections:
      - role: master
        host: localhost
      - role: slave
        host: localhost

Any help would be great, i've been struggling for a few days on this.

Thanks!

**Comment by mnelson** [comment]
It's because of activerecord-import. It expects a non-standard location for the adapter. You can define that location in your app if you'd like. 

https://github.com/zdennis/activerecord-import/blob/master/README.markdown#additional-adapters

**Comment by smikkelsen** [comment]
OOOHHHH... i was looking in the wrong place, that makes total sense.

I've gone through the readme you sent, i'm not quite sure how to fix it.

Do I just call something like this?
ActiveRecord::Import.require_adapter('mysql2_makara')

And where do i put it?

Sorry for the newb questions and thanks a lot for your help. I'm excited to start using makara!
