### ISSUE TITLE
support multiple databases

### ISSUE THREAD

**Issue by kshahkshah** [taskrabbit/makara#65]
I am starting to use Makara - I am having no issues connecting to my pg master / dual pg slave on my main app's database.

However, we, like many other apps out there rely on multiple databases, our app servers from our main database and our workers consume data from a vendor database using establish_connection on AR models as such:

```
class VendorDataModel < ActiveRecord::Base
  establish_connection "#{Rails.env}_vendor_data"
end
```

It looks like this call no longer has any effect (Rails 4.1.8)

```
VendorDataModel.establish_connection
VendorDataModel.first # will result in an error, no such relation...
```

I'm about to dive into the code, but perhaps someone can let me know - is this supported and undocumented, if it isn't supported would you accept a patch?

Manually running:

```
connection = ActiveRecord::Base.establish_connection(...YAML...)[Rails.env]
```

Appears to work fine however.

Can anyone provide some insight?

**Comment by kshahkshah** [comment]
Nope!! This was entirely my error. Insight is I need to be more careful

**Comment by MatTarantini** [comment]
What ended up being the solution here?
