### ISSUE TITLE
postgis adapter

### ISSUE THREAD

**Issue by dvodvo** [taskrabbit/makara#67]
Wanting to try out makara, I noticed that `/lib/active_record/connection_adapters` has a slew of adapters for cases where users shuffle `makara` and the adapter around.

However, having to use the postgis-adapted version of postgresql  ( https://github.com/rgeo/activerecord-postgis-adapter ) the database.yml file will need to refer to the adapter as `postgis`

I expect this will lead to a failure of sorts for makara to run properly. Any thoughts on how to face this issue and possible consequences?

**Comment by mnelson** [comment]
A makara postgis adapter would have to be implemented. It would be named `postgis_makara` and follow the same form as the `mysql_makara` adapter.

**Comment by dvodvo** [comment]
The activerecord-postgis-adapter gem installs the _postgis_  connection adapter into ActiveRecord.  So then the file would go on:
require 'active_record/connection_adapters/makara_abstract_adapter'
require 'active_record/connection_adapters/postgis_adapter'
if ActiveRecord::VERSION::MAJOR >= 4
module ActiveRecord
module ConnectionHandling
def postgis_makara_connection(config)
ActiveRecord::ConnectionAdapters::MakaraPostgisAdapter.new(config)
end
end
end
    etc. ?

**Comment by mnelson** [comment]
That looks correct.

**Comment by dvodvo** [comment]
So to get this working, I would need to fork the repo, add the file(s) and test (not really done that before!)
anything else I'm missing?

**Comment by mnelson** [comment]
Yeah, make your fork & get it working locally. There are adapter-specific tests already which you can pretty much copy / paste. Then we'll have to get travis to accommodate the new requirements. Should be too complicated http://mattmakesmaps.com/blog/2014/01/11/configure-postgis-with-travis-ci/

**Comment by dvodvo** [comment]
I knew I was in over my head. I sort of confirmed it overnight.  This is not a task I am qualified to do.  In any instance there are two ways the project I am concerned with can proceed.  One is by using the postgresql adapter in the main application.  However, even there I am hitting issues.  I'll check first if it's been approached before posting a new one.  On this matter, maybe the discussion can be moved off to e-mail...
