### ISSUE TITLE
makara installs locally but cannot deploy

### ISSUE THREAD

**Issue by dvodvo** [taskrabbit/makara#68]
Under `.rvm/rubies/ruby-1.9.3-p550` for a rails3.2.18 app bundle install command executes completely with the following syntax  
`gem 'makara', :github => 'taskrabbit/makara', :branch => '~> 0.3.0'`  

  However upon deployment rake aborts
`rake aborted!
Please install the postgresql_makara adapter:`gem install activerecord-postgresql_makara-adapter`(cannot load such file -- active_record/connection_adapters/postgresql_makara_adapter)`
The `gem install command` does not run as it is not listed in rubygems.

**Comment by mnelson** [comment]
Are you using Bundler.require or Bundler.setup? In any case, `require 'makara`` before your use of ActiveRecord should do the trick.

**Comment by dvodvo** [comment]
Progress. Capfile now amended with `require 'capistrano/bundler'
require 'makara'
require 'capistrano/rails'`
one obstacle overcome; however `rake aborted!
fe_sendauth: no password supplied`

**Comment by dvodvo** [comment]
I guess the makara connection behaves somewhat differently (proxy?) from the normal postgresql connection: I did not have the password defined in the traditional non-replicated context.
