### ISSUE TITLE
Clarity in Basic Usage instructions

### ISSUE THREAD

**Issue by dvodvo** [taskrabbit/makara#69]
The Basic Usage section of the repo's README has a `here you go.` link.  Which this set of eyes went towards... and skip what follows.  Thus, for one who is coming in from left field regarding AR and connections, I just don't know what to make of what follows.

a class needs to be defined `class MyAwesomeSqlProxy < ::Makara::Proxy`.  OK.  where? in an initialiser? I gather  hijack_method is meant to send all selects to the slave.  Where can I document myself to understand better :connect, :reconnect, etc. and thus make appropriate choices?

Reason being is that from the slave, I'm hitting `Processing by Devise::SessionsController#create as HTML [...] ActiveRecord::StatementInvalid (PG::ReadOnlySqlTransaction: ERROR:  cannot execute UPDATE in a read-only transaction`, so clearly no hijacking is going on!  Am also curious about the host (it could be a 3rd level domain, but I assume it is quicker to have the relevant server's ip-address and the web server (nginx) point the default configuration to the proper app - or am I mis-assuming?

**Comment by mnelson** [comment]
I believe all that your project requires is in the "here you go" section of the readme. If you need postgis I would make sure that everything is functional with the default postgis adapter before thinking about utilizing makara.

**Comment by dvodvo** [comment]
In order to address this, I am going at it gradually.  I am only attempting to connect via postgreSQL adapter for the time being. So I'm obviously doing something wrong given the `ActiveRecord::StatementInvalid (PG::ReadOnlySqlTransaction: ERROR: cannot execute UPDATE in a read-only transaction` error...  the database.yml seems to be insufficient to get things rolling...
